// Auto-generated by scripts/generate-versions.cjs
// DO NOT EDIT MANUALLY

export const versions = {
  buildVersion: '1.1.0',
  frontendVersion: '1.1.0',
  backendVersion: '1.0.0',
  cliVersion: '1.0.1',
  buildDate: '2026-03-27T06:11:06.879Z',
} as const;

export type Versions = typeof versions;
